version: '3.3'
services: 
    web:
        container_name: flask-container 
        build: 
            context: ./services/web
            dockerfile: Dockerfile
        command: python manage.py run -h 0.0.0.0
        expose: 
            - 5000
        env_file:  
            - ./.env.dev
        depends_on: 
            - db 

    db:
        container_name: postgres-container
        image: postgres:13-alpine
        volumes: 
            - ./postgres_data:/var/lib/postgresql/data/
        environment: 
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root 
            - POSTGRES_DB=my_db

    nginx:
        container_name: nginx-container
        build: 
            context: ./services/nginx
            dockerfile: Dockerfile
        ports: 
            - 1337:80
        depends_on: 
            - web

volumes: 
    postgres_data: